export JWT_EXPIRE_HOURS=720

export JWT_PRIVATE_PEM="-----BEGIN RSA PRIVATE KEY-----
MD0CAQACCQCb7CeZsbzMfQIDAQABAghDSOhZLTYH4QIFAMR4MKUCBQDLKsz5AgRH
00S9AgQ5m6ZJAgRwBrSH
-----END RSA PRIVATE KEY-----"

export JWT_PUBLIC_PEM="-----BEGIN RSA PUBLIC KEY-----
MBACCQCb7CeZsbzMfQIDAQAB
-----END RSA PUBLIC KEY-----"